fixtures:
  forge_modules:
    powershell:
      repo: "puppetlabs/powershell"
      ref: "5.2.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "9.7.0"
  # repositories:
  #   my_custom_module:
  #     repo: "https://github.com/myorg/my_custom_module.git"
  #     ref: "main"
  # symlinks:
  #   my_local_module: "#{source_dir}/../my_local_module"